---
name: Continuous Integration
on:
  - pull_request
  - workflow_dispatch
env:
  MODEL_URL: https://huggingface.co/TheBloke/CodeLlama-7B-GGUF/resolve/main/codellama-7b.Q2_K.gguf
  MODEL_NAME: codellama-7b.Q2_K.gguf
jobs:
  build-and-test-linux:
    name: ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: "11"
      - name: Install libcurl
        run: sudo apt-get install -y libcurl4-openssl-dev
      - name: Build libraries
        run: |
          mvn compile
          .github/build.sh -DLLAMA_VERBOSE=ON -DLLAMA_CURL=ON
      - name: Download model
        run: curl -L ${MODEL_URL} --create-dirs -o models/${MODEL_NAME}
      - name: Run tests
        run: mvn test
      - if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: error-log-linux
          path: ${{ github.workspace }}/hs_err_pid*.log
          if-no-files-found: warn
  build-and-test-macos:
    name: ${{ matrix.target.runner }}
    runs-on: ${{ matrix.target.runner }}
    strategy:
      fail-fast: false
      matrix:
        target:
          - runner: macos-13
            cmake: -DLLAMA_METAL=OFF -DLLAMA_VERBOSE=ON -DLLAMA_CURL=ON
          - runner: macos-14
            cmake: -DLLAMA_METAL_EMBED_LIBRARY=ON -DLLAMA_METAL=OFF -DLLAMA_VERBOSE=ON
              -DLLAMA_CURL=ON
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: "11"
      - name: Build libraries
        run: |
          mvn compile
          .github/build.sh ${{ matrix.target.cmake }}
      - name: Download model
        run: curl -L ${MODEL_URL} --create-dirs -o models/${MODEL_NAME}
      - name: Run tests
        run: mvn test
      - if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: error-log-macos
          path: ${{ github.workspace }}/hs_err_pid*.log
          if-no-files-found: warn
  build-and-test-windows:
    name: windows-latest
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: "11"
      - name: Install libcurl and dependencies
        run: >
          vcpkg install curl:x64-windows

          vcpkg install openssl:x64-windows

          vcpkg install zlib:x64-windows

          vcpkg install boost-filesystem:x64-windows  # Often needed for C++ projects

          vcpkg install boost-system:x64-windows      # Often needed for C++ projects
      - name: Download Dependency Walker
        run: >
          Invoke-WebRequest -Uri "https://www.dependencywalker.com/depends22_x64.zip"
          -OutFile "depends.zip"

          Expand-Archive -Path "depends.zip" -DestinationPath "depends"
          # Verify it was extracted correctly
          dir depends
      - name: Build libraries
        run: >
          mvn compile

          .github\build.bat -DLLAMA_VERBOSE=ON -DLLAMA_CURL=ON -DCURL_LIBRARY=C:/vcpkg/packages/curl_x64-windows/lib/libcurl.lib -DCURL_INCLUDE_DIR=C:/vcpkg/packages/curl_x64-windows/include
      - name: Prepare DLL directory
        run: >
          mkdir -Force "target/classes/de/kherud/llama/Windows/x86_64"

          Copy-Item ".\src\main\resources\de\kherud\llama\Windows\x86_64\*.dll" "target/classes/de/kherud/llama/Windows/x86_64/"


          #Copy ALL DLLs from vcpkg directories to ensure we have everything

          Get-ChildItem "C:/vcpkg/installed/x64-windows/bin" -Filter *.dll | ForEach-Object { 

          Copy-Item $_.FullName -Destination "target/classes/de/kherud/llama/Windows/x86_64/" -Verbose 

          }


          # Also from the packages directory

          Get-ChildItem "C:/vcpkg/packages" -Recurse -Filter "*.dll" | Where-Object { $_.Directory -like "*bin*" } | ForEach-Object {

          Copy-Item $_.FullName -Destination "target/classes/de/kherud/llama/Windows/x86_64/" -Verbose

          }


          # Copy Visual C++ Redistributable DLLs

          $vcredistPath = "C:\Windows\System32"

          @(
            "msvcp140.dll", 
            "vcruntime140.dll", 
            "vcruntime140_1.dll",
            "msvcp140_1.dll",
            "msvcp140_2.dll",
            "concrt140.dll"
          ) | ForEach-Object {
            if (Test-Path "$vcredistPath\$_") {
              Copy-Item "$vcredistPath\$_" -Destination "target/classes/de/kherud/llama/Windows/x86_64/" -Verbose
            }
          }
      - name: Analyze DLL dependencies
        run: |
          # Create directory for outputs
          mkdir -Force "dependency_reports"
    
          # Get paths to DLLs for analysis
          $ggmlPath = "${{ github.workspace }}\target\classes\de\kherud\llama\Windows\x86_64\ggml.dll"
          $llamaPath = "${{ github.workspace }}\target\classes\de\kherud\llama\Windows\x86_64\llama.dll"
          $jllamaPath = "${{ github.workspace }}\target\classes\de\kherud\llama\Windows\x86_64\jllama.dll"
    
          # Verify files exist before analysis
          Write-Host "Verifying DLL files exist:"
          if (Test-Path $ggmlPath) { Write-Host "ggml.dll exists at $ggmlPath" } else { Write-Host "ERROR: ggml.dll NOT FOUND at $ggmlPath" }
          if (Test-Path $llamaPath) { Write-Host "llama.dll exists at $llamaPath" } else { Write-Host "ERROR: llama.dll NOT FOUND at $llamaPath" }
          if (Test-Path $jllamaPath) { Write-Host "jllama.dll exists at $jllamaPath" } else { Write-Host "ERROR: jllama.dll NOT FOUND at $jllamaPath" }

          # Alternative approach using dumpbin (available on Windows)
          Write-Host "Analyzing dependencies with dumpbin..."
    
          # Create a function to extract dependencies
          function Get-Dependencies {
            param([string]$dllPath, [string]$outputPath)
      
            if (Test-Path $dllPath) {
              Write-Host "Running dumpbin on $dllPath"
              & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64\dumpbin.exe" /DEPENDENTS $dllPath > $outputPath
              if ($LASTEXITCODE -eq 0) {
                Write-Host "Successfully wrote dependencies to $outputPath"
                Get-Content $outputPath | Select-String -Pattern "Image has the following dependencies"
                Get-Content $outputPath | Select-String -Pattern "\.dll"
              } else {
                Write-Host "Error running dumpbin: $LASTEXITCODE"
              }
            } else {
               Write-Host "ERROR: File not found: $dllPath"
            }
          }  
    
          # Run dependency analysis
          Get-Dependencies -dllPath $ggmlPath -outputPath "dependency_reports\deps_ggml.txt"
          Get-Dependencies -dllPath $llamaPath -outputPath "dependency_reports\deps_llama.txt"
          Get-Dependencies -dllPath $jllamaPath -outputPath "dependency_reports\deps_jllama.txt"
    
          # List files in the output directory
          Write-Host "Files in dependency_reports directory:"
          dir dependency_reports

      - name: Upload dependency reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dependency-reports
          path: dependency_reports\*
          if-no-files-found: warn
          
      - name: Verify DLL placement
        run: |
          dir target\classes\de\kherud\llama\Windows\x86_64\
      - name: Download model
        run: curl -L $env:MODEL_URL --create-dirs -o models/$env:MODEL_NAME
      - name: Run tests with explicit DLL path
        run: >
          $env:PATH = "C:\vcpkg\installed\x64-windows\bin;${env:PATH}"

          mvn test  "-Djava.library.path=${env:PATH};target/classes/de/kherud/llama/Windows/x86_64" -Ddebug.native.loading=true
      - if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: error-log-windows
          path: ${{ github.workspace }}\hs_err_pid*.log
          if-no-files-found: warn

