name: Build JNI bindings and publish to Maven Central
on:
  workflow_dispatch:
  release:
    types: [created]
jobs:
  build:
    name: Build ${{ matrix.target.name }}-${{ matrix.target.arch }}
    runs-on: ${{ matrix.target.image }}
    strategy:
      fail-fast: false
      matrix:
        target:
          - {
            name: Linux,
            arch: x86_64,
            image: ubuntu-latest,
            cmake: "-DCMAKE_CXX_FLAGS='-march=x86-64' -DLLAMA_NATIVE=OFF"
          }
          - {
            name: Mac,
            arch: x86_64,
            image: macos-latest,
            cmake: "-DCMAKE_OSX_ARCHITECTURES=x86_64 -DLLAMA_NATIVE=OFF"
          }
          - {
            name: Mac,
            arch: aarch64,
            image: macos-latest,
            cmake: "-DCMAKE_OSX_ARCHITECTURES=arm64 -DLLAMA_NATIVE=OFF"
          }
          - {
            name: Windows,
            arch: x86_64,
            image: windows-latest,
            cmake: "-DCMAKE_GENERATOR_PLATFORM=x64"
          }
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: CMake (Windows)
        if: ${{ matrix.target.name == 'Windows' }}
        shell: cmd
        run: |
          cd scripts && .\build.bat ${{ matrix.target.cmake }} -DOS_NAME=${{ matrix.target.name }} -DOS_ARCH=${{ matrix.target.arch }}
      - name: CMake (Unix)
        if: ${{ matrix.target.name != 'Windows' }}
        shell: bash
        run: |
          cd scripts && ./build.sh ${{ matrix.target.cmake }} -DOS_NAME=${{ matrix.target.name }} -DOS_ARCH=${{ matrix.target.arch }}
      - name: Upload Windows Artifact
        if: ${{ matrix.target.name == 'Windows' }}
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: ${{ github.workspace }}\src\main\resources\de\kherud\llama\
      - name: Upload Unix Artifact
        if: ${{ matrix.target.name != 'Windows' }}
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: ${{ github.workspace }}/src/main/resources/de/kherud/llama/
  build-linux-arm64:
    name: Build Linux-aarch64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/arm64
      - name: CMake (Linux)
        run: |
          docker run \
            --rm \
            -v $(pwd):/${{ github.workspace }} \
            -w ${{ github.workspace }} \
            --platform linux/arm64 \
            eclipse-temurin:11 \
            sh -c "apt-get update && apt-get install -y cmake openjdk-11-jdk git build-essential && cd scripts && ./build.sh -DCMAKE_CXX_FLAGS='-march=armv8-a' -DOS_NAME=Linux -DOS_ARCH=aarch64"
            # The above apt-get commands can be moved to a Dockerfile, but then
            # the image needs to be built for the docker-arch architecture,
            # which means using the docker/setup-buildx-action
      - name: Upload Unix Artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: ${{ github.workspace }}/src/main/resources/de/kherud/llama/
  publish:
    needs: [build,build-linux-arm64]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifacts
          path: ${{ github.workspace }}/src/main/resources/de/kherud/llama/
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_SIGNING_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: Publish package
        run: mvn --batch-mode -P release deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
